# change the followings to match your Github username and repo name
baseurl: "/technicallyaPodcast" # the name of your github repo
url: "https://mia-ktlk.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Technically a Podcast hosted by Mia Kotalik"
description: Tech and Business Podcasts by Mia

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Mia Kotalik
author-bio: Podcast Host # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: https://facebook.com/
instagram: https://www.instagram.com/helloitsmia.tech/
github: false
linkedin: https://www.linkedin.com/in/miakotalik/
medium: https://helloitsmia.medium.com/
google-scholar: false
email: false

# footer information
footer-msg: "Made with ♥ by Mia"
footer-msg-link: https://miakotalik.com/

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
